Feature 3 (#3)
* Initial

* Readme

* Intentional Workflow Failure

diff --git a/.github/workflows/nodeCI.yaml b/.github/workflows/nodeCI.yaml
--- a/.github/workflows/nodeCI.yaml
+++ b/.github/workflows/nodeCI.yaml
@@ -1,28 +1,18 @@
-name: Pull Request Check
+name: Workflow Failure
  
+
 on:
   pull_request:
     branches:
       - main
- 
+
 jobs:
-  build:
-    name: pull-request-checker
+  test:
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        node-version: [20.x]
+
     steps:
-      - uses: actions/checkout@v2
- 
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v2
-        with:
-          node-version: ${{ matrix.node-version }}
-          cache: 'npm'
- 
-      - name: Install Node Packages
-        run: npm install
- 
-      - name: Print Hello!
-        run: echo "Hello!"
+
+      # Intentionally failing step
+      - name: Intentional Failure
+        run: exit 1
+
